name: 'auto deploy'
on:
  push:
    branches:
      - main
jobs:
  Auto-Deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 14
      - run: npm ci
      - run: npm run build